name: Release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"
        token: ${{ secrets.GHCR_TOKEN }}
    - uses: fusion-engineering/setup-git-credentials@v2
      with:
        credentials: ${{ format('https://x-access-token:{0}@github.com/', secrets.GHCR_TOKEN) }}
    - id: prep
      name: Set the release version
      uses: docker://gcr.io/jenkinsxio/jx-release-version:1.0.46
      with:
        args: -c "echo ::set-output name=version::$(jx-release-version)"
        entrypoint: bash
    - env:
        VERSION: ${{ steps.prep.outputs.version }}
      run: |
        echo "tagging version $VERSION"
        git config --global user.email "james.strachan@gmail.com"
        git config --global user.name "jstrachan"
        git tag -fa v$VERSION -m "Release version $VERSION"
        git push --force origin v$VERSION
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        build-args: |
          VERSION=${{ steps.prep.outputs.version}}
        tags: |
          ghcr.io/jenkins-x/serverless-ci:latest
          ghcr.io/jenkins-x/serverless-ci:${{ steps.prep.outputs.version }}
"on":
  push:
    branches:
    - main
    - master
